//
//  SummaryViewController.swift
//  ANSD_APP
//
//  Created by Anshul Kumaria on 25/11/25.
//

import UIKit
import PDFKit

class SummaryViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, NotesCardCellDelegate, SummaryCardDelegate {
    
    @IBOutlet weak var tableView: UITableView!
    
    @IBOutlet weak var optionsButton: UIBarButtonItem!
    
    var conversationTitle = "New Conversation"
    
    var participantsData: [ParticipantData] = [
            ParticipantData(
                name: "Peter Parker",
                initials: "PP",
                summary: "Peter has gotten a look at some alleged photos from the set of Avengers Doomsday, and thinks that they are real."
            ),
            ParticipantData(
                name: "Bruce Banner",
                initials: "BB",
                summary: "Bruce thinks that they are either a photo-shop, and his words imply that he doesn't believe it to be genuine."
            ),
            ParticipantData(
                name: "Steve",
                initials: "SP",
                summary: "Steve has dismissed it as fan-fiction or an image generated by Google Gemini."
            )
        ]
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .systemGroupedBackground
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.backgroundColor = .clear
        
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 120
        
        let tap = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard))
        tap.cancelsTouchesInView = false
        view.addGestureRecognizer(tap)
        
        setupOptionsMenu()
    }
    
    @objc func dismissKeyboard() {
        view.endEditing(true)
    }
    
    // MARK: - Actions
    
    @IBAction func backTapped(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
    
    // MARK: - The Menu Logic (Top Right)
    func setupOptionsMenu() {
        
        let shareAction = UIAction(title: "Share / Export", image: UIImage(systemName: "square.and.arrow.up")) { [weak self] _ in
            self?.showExportPopup()
        }
        
        let endAction = UIAction(title: "End Session", image: UIImage(systemName: "xmark.circle"), attributes: .destructive) { [weak self] _ in
                    guard let self = self else { return }
                    

                    if let navController = self.view.window?.rootViewController as? UINavigationController {
                        
                        navController.popToRootViewController(animated: false)
                        
                        navController.dismiss(animated: true, completion: nil)
                    }
                }
        
        let menu = UIMenu(title: "", children: [shareAction, endAction])
        
        optionsButton.menu = menu
    }

    // MARK: - Helper: The Export Pop-up
    func showExportPopup() {
        let alert = UIAlertController(title: "Export Summary", message: "Choose a format to share", preferredStyle: .alert)
        
        alert.addAction(UIAlertAction(title: "Share as Text", style: .default, handler: { _ in
            self.shareAsText()
        }))
        
        alert.addAction(UIAlertAction(title: "Share as PDF", style: .default, handler: { _ in
            self.shareAsPDF()
        }))
        
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
        
        self.present(alert, animated: true)
    }

    // MARK: - Logic 1: Share Plain Text
    func shareAsText() {
        var fullText = "Conversation Title: \(conversationTitle)\n\n"
        for person in participantsData {
            fullText += "\(person.name) (\(person.initials)):\n\(person.summary)\n\n"
        }
        
        let activityVC = UIActivityViewController(activityItems: [fullText], applicationActivities: nil)
        activityVC.popoverPresentationController?.sourceView = self.view
        self.present(activityVC, animated: true)
    }
    
    // MARK: - Logic 2: Share PDF
    func shareAsPDF() {
        var pdfContent = "Conversation Title: \(conversationTitle)\n\n"
        for person in participantsData {
            pdfContent += "\(person.name) (\(person.initials)):\n\(person.summary)\n\n"
        }
        
        if let pdfURL = createPDF(from: pdfContent) {
            let activityVC = UIActivityViewController(activityItems: [pdfURL], applicationActivities: nil)
            activityVC.popoverPresentationController?.sourceView = self.view
            self.present(activityVC, animated: true)
        }
    }
    
    // MARK: - PDF Generator Helper
    func createPDF(from text: String) -> URL? {
        let pageWidth = 595.2
        let pageHeight = 841.8
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        
        let data = renderer.pdfData { (context) in
            context.beginPage()
            
            let attributes = [
                NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12),
                NSAttributedString.Key.paragraphStyle: NSMutableParagraphStyle()
            ]
            
            let textRect = CGRect(x: 40, y: 40, width: pageWidth - 80, height: pageHeight - 80)
            text.draw(in: textRect, withAttributes: attributes)
        }
        
        let tempFolder = FileManager.default.temporaryDirectory
        let fileName = "\(conversationTitle) - Summary.pdf"
        let fileURL = tempFolder.appendingPathComponent(fileName)
        
        do {
            try data.write(to: fileURL)
            return fileURL
        } catch {
            print("Error generating PDF: \(error)")
            return nil
        }
    }
    
    // MARK: - Table View Data Source
    func numberOfSections(in tableView: UITableView) -> Int {
        return 6
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 3 { return participantsData.count }
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        switch indexPath.section {
        case 0:
            let cell = tableView.dequeueReusableCell(withIdentifier: "SummarySectionHeaderCell", for: indexPath) as! SummarySectionHeaderCell
            cell.headerLabel.text = "Conversation Summary"
            cell.headerIcon.image = UIImage(systemName: "list.bullet.clipboard")
            return cell
            
        case 1:
            let cell = tableView.dequeueReusableCell(withIdentifier: "SummaryCardCell", for: indexPath) as! SummaryCardCell
            // Load Title
            cell.titleTextField.text = conversationTitle
            cell.delegate = self
            return cell
            
        case 2:
            let cell = tableView.dequeueReusableCell(withIdentifier: "ParticipantsSummaryHeaderCell", for: indexPath) as! ParticipantsSummaryHeaderCell
            return cell
            
        case 3:
            let cell = tableView.dequeueReusableCell(withIdentifier: "ParticipantsCardCell", for: indexPath) as! ParticipantCardCell
            let data = participantsData[indexPath.row]
            cell.configure(with: data)
            return cell
            
        case 4:
            let cell = tableView.dequeueReusableCell(withIdentifier: "SummarySectionHeaderCell", for: indexPath) as! SummarySectionHeaderCell
            cell.headerLabel.text = "Notes"
            cell.headerIcon.image = UIImage(systemName: "note.text")
            return cell
            
        case 5:
            let cell = tableView.dequeueReusableCell(withIdentifier: "NotesCardCell", for: indexPath) as! NotesCardCell
            cell.delegate = self
            return cell
            
        default:
            return UITableViewCell()
        }
    }
    
    // MARK: - Delegates
    
    func didUpdateText(in cell: NotesCardCell) {
        tableView.performBatchUpdates(nil, completion: nil)
        if let indexPath = tableView.indexPath(for: cell) {
            tableView.scrollToRow(at: indexPath, at: .bottom, animated: false)
        }
    }
    
    func didChangeTitle(text: String) {
        conversationTitle = text
    }
}
